#!/usr/bin/env bash
# Generating the notification bundle -- the .app that owns memcap's notification
# icon. Sourced only by the commands that can build one (init, watch, notify);
# common.sh knows where the bundle lives and how to post through it, which is all
# the enforcement path needs.
set -uo pipefail

# A notification's icon follows the POSTING BUNDLE, not the notification.
# AppleScript's `display notification` has no icon parameter, and a plain
# `osascript` call is attributed to Script Editor -- whose icon is what memcap
# showed for its entire life, on notifications about processes it had just
# killed. The only way to change it is to post from a bundle memcap owns.
#
# So init compiles one. Everything involved ships with macOS (osacompile,
# osascript, sips, iconutil, codesign), which is what keeps a shell-script repo
# free of a checked-in binary asset: the icon is rendered from a single emoji at
# install time. Failing to build one is never fatal -- mc_notify falls back to
# the plain osascript path, which is exactly what every version before this did.
MC_NOTIFIER_FORMAT=1
MC_NOTIFY_ICON_DEFAULT='🧠'

# Bumping MC_NOTIFIER_FORMAT is what makes an upgraded memcap replace a bundle
# generated by an older one. The stamp records both, so a changed NOTIFY_ICON and
# a changed bundle layout are the same kind of event.
mc_notifier_stamp() { printf '%s/notifier-stamp\n' "$(mc_state_dir)"; }

# The configured icon, or the default. Returns EMPTY for `NOTIFY_ICON=none`,
# which is the documented way to switch the bundle off entirely and keep the
# plain Script Editor notifications.
#
# Validated for the same reason EXTRA_AGENTS is (contract C3): this value is
# passed to a subprocess and rendered into a file path's worth of tooling. It is
# passed as an ARGUMENT rather than spliced into the JXA source, so quoting is
# not the exposure -- a control character reaching `sips` or a multi-kilobyte
# "emoji" is.
mc_notify_icon() {
  local icon="${NOTIFY_ICON-}" bytes safe ctrl
  case "$icon" in
    '') printf '%s' "$MC_NOTIFY_ICON_DEFAULT"; return 0 ;;
    none|NONE|None) return 0 ;;
  esac
  bytes=$(printf '%s' "$icon" | wc -c | tr -d ' ')
  # LC_ALL=C, and an explicit byte range rather than [[:cntrl:]]: in a UTF-8
  # locale that class matches ZERO WIDTH JOINER, so `[[:cntrl:]]` rejected
  # 👨‍👩‍👧‍👦 -- a perfectly ordinary icon -- as a control character. What actually
  # matters here is a raw ASCII control byte reaching a log line or an argv,
  # and every byte of a UTF-8 emoji is >= 0x80.
  ctrl=$(printf '%s' "$icon" | LC_ALL=C tr -cd '\001-\037\177')
  if [ -z "$ctrl" ] && [ "$bytes" -le 32 ]; then
    printf '%s' "$icon"
    return 0
  fi
  # The rejected value goes into the log line, so strip what made it unusable
  # rather than writing a control character into actions.log.
  safe=$(printf '%s' "$icon" | LC_ALL=C tr -d '\001-\037\177' | cut -c1-32)
  mc_log_throttled "$(mc_throttle_key NOTIFY_ICON)" \
    "config: NOTIFY_ICON is not a usable icon ('$safe') -- using $MC_NOTIFY_ICON_DEFAULT"
  printf '%s' "$MC_NOTIFY_ICON_DEFAULT"
  return 0
}

# Emoji glyph -> .icns, via AppKit through JXA. The alternative was shipping an
# .icns in the repo, which fixes the icon for everyone and puts a binary in a
# tree that is otherwise entirely shell.
#
# NSImage's lockFocus needs a window server connection, so this is the one step
# that can fail on a machine where everything else works (a headless CI runner,
# an ssh session with no GUI login). It reports that failure rather than
# producing a bundle with a default icon that would look like the feature simply
# did not work.
mc_notifier_render_icns() {
  local icon="$1" out="$2" tmp sz rc=0
  command -v osascript >/dev/null 2>&1 || return 1
  command -v sips >/dev/null 2>&1 || return 1
  command -v iconutil >/dev/null 2>&1 || return 1

  tmp=$(mktemp -d "${TMPDIR:-/tmp}/memcap-icon.XXXXXX") || return 1

  cat > "$tmp/render.js" <<'JS'
ObjC.import('AppKit');
// argv[0..3] are osascript's own: the binary, -l, JavaScript, and this script.
var argv = $.NSProcessInfo.processInfo.arguments;
var emoji = ObjC.unwrap(argv.objectAtIndex(4));
var size = parseInt(ObjC.unwrap(argv.objectAtIndex(5)), 10);
var out = ObjC.unwrap(argv.objectAtIndex(6));
var font = $.NSFont.fontWithNameSize($('AppleColorEmoji'), size * 0.8);
var attrs = $({ NSFont: font });
var glyph = $(emoji);
var box = glyph.sizeWithAttributes(attrs);
var img = $.NSImage.alloc.initWithSize({ width: size, height: size });
img.lockFocus;
glyph.drawAtPointWithAttributes(
  { x: (size - box.width) / 2, y: (size - box.height) / 2 }, attrs);
img.unlockFocus;
var rep = $.NSBitmapImageRep.imageRepWithData(img.TIFFRepresentation);
var png = rep.representationUsingTypeProperties($.NSBitmapImageFileTypePNG, $());
png.writeToFileAtomically($(out), true);
JS

  # Rendered at 512 points, which a Retina backing store makes 1024 pixels --
  # the size icon_512x512@2x needs, and the largest iconutil will accept here.
  if ! osascript -l JavaScript "$tmp/render.js" "$icon" 512 "$tmp/icon.png" >/dev/null 2>&1; then
    rm -rf "$tmp"
    return 1
  fi
  [ -s "$tmp/icon.png" ] || { rm -rf "$tmp"; return 1; }

  mkdir -p "$tmp/icon.iconset"
  for sz in 16 32 128 256 512; do
    sips -z "$sz" "$sz" "$tmp/icon.png" \
      --out "$tmp/icon.iconset/icon_${sz}x${sz}.png" >/dev/null 2>&1 || rc=1
    sips -z $((sz * 2)) $((sz * 2)) "$tmp/icon.png" \
      --out "$tmp/icon.iconset/icon_${sz}x${sz}@2x.png" >/dev/null 2>&1 || rc=1
  done
  if [ "$rc" != "0" ] || ! iconutil -c icns "$tmp/icon.iconset" -o "$out" >/dev/null 2>&1; then
    rm -rf "$tmp"
    return 1
  fi
  rm -rf "$tmp"
  [ -s "$out" ]
}

# Compile the applet, give it the icon, and swap it into place.
#
# The applet reads its message from a file rather than taking it as an argument:
# `open --args` does not reach an applet's `run` handler on macOS 26 (it arrives
# as something `item 1 of argv` cannot coerce, and AppleScript reports that in a
# MODAL DIALOG -- a notification path whose failure mode is an alert box the user
# has to dismiss is worse than no notification at all).
mc_build_notifier() {
  local icon app bundle script msg_file rc
  icon="$(mc_notify_icon)"
  app="$(mc_notifier_app)"

  if [ -z "$icon" ]; then
    mc_remove_notifier
    return 0
  fi
  if ! command -v osacompile >/dev/null 2>&1 || ! command -v codesign >/dev/null 2>&1; then
    mc_log "notify: osacompile or codesign is unavailable -- keeping the plain notification path"
    return 1
  fi
  mkdir -p "$(mc_state_dir)" 2>/dev/null || return 1

  # Built beside the real one and moved into place. The staging name keeps the
  # `.app` extension because osacompile switches on it: given an output path
  # ending in anything else it writes a compiled SCRIPT FILE instead of an
  # applet bundle, and every bundle edit below then fails against a plain file.
  bundle="$(mc_state_dir)/Notifier.new.app"
  rm -rf "$bundle"
  msg_file="$(mc_notifier_message_file)"
  # The message file's path is baked in at build time because the applet cannot
  # see MEMCAP_STATE_HOME -- it is launched by launchservices, not by memcap's
  # own shell. mc_as_quote is the same escaping the plain path uses.
  script="on run
	set msg to \"memcap\"
	try
		set msg to (read (POSIX file \"$(mc_as_quote "$msg_file")\") as «class utf8»)
	end try
	display notification msg with title \"memcap\"
end run"

  if ! osacompile -o "$bundle" -e "$script" >/dev/null 2>&1; then
    mc_log "notify: osacompile failed -- keeping the plain notification path"
    rm -rf "$bundle"
    return 1
  fi

  # osacompile ships an Assets.car holding the stock applet icon, and
  # CFBundleIconName (which points into it) WINS over CFBundleIconFile. Replacing
  # applet.icns without removing both leaves the generic AppleScript icon in
  # place and looks exactly like a rendering failure.
  rm -f "$bundle/Contents/Resources/Assets.car"
  # `|| :` on every one: a key that is already absent makes Delete fail, and a
  # caller running under `set -e` would take that as a reason to abort a build
  # that is going perfectly well. The signature check below is what actually
  # proves the bundle came out usable.
  /usr/libexec/PlistBuddy -c "Delete :CFBundleIconName" "$bundle/Contents/Info.plist" >/dev/null 2>&1 || :
  /usr/libexec/PlistBuddy -c "Set :CFBundleName memcap" "$bundle/Contents/Info.plist" >/dev/null 2>&1 || :
  /usr/libexec/PlistBuddy -c "Add :CFBundleIdentifier string com.memcap.notifier" "$bundle/Contents/Info.plist" >/dev/null 2>&1 ||
    /usr/libexec/PlistBuddy -c "Set :CFBundleIdentifier com.memcap.notifier" "$bundle/Contents/Info.plist" >/dev/null 2>&1 || :
  # Without this the applet bounces in the Dock on every notification.
  /usr/libexec/PlistBuddy -c "Add :LSUIElement string 1" "$bundle/Contents/Info.plist" >/dev/null 2>&1 || :

  if ! mc_notifier_render_icns "$icon" "$bundle/Contents/Resources/applet.icns"; then
    mc_log "notify: could not render the $icon icon (no window server?) -- keeping the plain notification path"
    rm -rf "$bundle"
    return 1
  fi

  # osacompile ad-hoc signs what it writes, so every edit above invalidated that
  # signature. An applet whose signature does not match its resources is killed
  # on launch rather than run, which would make notifications vanish silently.
  if ! codesign --force -s - "$bundle" >/dev/null 2>&1; then
    mc_log "notify: could not re-sign the notifier bundle -- keeping the plain notification path"
    rm -rf "$bundle"
    return 1
  fi

  case "$app" in
    */Notifier.app) : ;;
    # Belt for the rm -rf below: mc_notifier_app is not user input, but this
    # function is the only place in memcap that removes a directory tree outside
    # `memcap uninstall`, and a path that is not the bundle must never reach it.
    *) mc_log "notify: refusing to replace an unexpected notifier path ($app)"; rm -rf "$bundle"; return 1 ;;
  esac
  rm -rf "$app"
  rc=0
  mv "$bundle" "$app" 2>/dev/null || rc=1
  if [ "$rc" != "0" ]; then
    rm -rf "$bundle"
    return 1
  fi
  mc_log "notify: built the notifier bundle with the $icon icon"
  return 0
}

mc_remove_notifier() {
  local app
  app="$(mc_notifier_app)"
  case "$app" in
    */Notifier.app) rm -rf "$app" "$(mc_state_dir)/Notifier.new.app" ;;
  esac
  return 0
}

# Cheap enough to call on every pass: one file read when nothing has changed.
#
# The stamp is written on FAILURE too. A machine that cannot render an icon
# cannot render it 1,440 times a day either, and retrying a ~2-second build on
# every 60-second pass would cost more than the feature is worth. A changed
# NOTIFY_ICON, or a memcap upgrade that bumps MC_NOTIFIER_FORMAT, both change the
# stamp and so both retry; `memcap notify` forces one on demand.
mc_ensure_notifier() {
  local icon want have rc=0 outcome
  [ "${MC_NO_NOTIFIER:-0}" = "1" ] && return 0
  icon="$(mc_notify_icon)"
  want="$MC_NOTIFIER_FORMAT ${icon:-none}"
  # `|| have=""`: a missing stamp is the ordinary first-run case, and under
  # `set -e` -- which every bats test runs with -- a bare assignment from a
  # failing command substitution aborts the caller instead.
  have=$(cat "$(mc_notifier_stamp)" 2>/dev/null) || have=""

  case "$have" in
    "$want ok")
      # Built, and still there. The app going missing on its own (a cleanup
      # tool, a half-finished restore) is worth rebuilding for.
      if [ -z "$icon" ] || [ -d "$(mc_notifier_app)" ]; then
        return 0
      fi
      ;;
    "$want failed")
      # Already tried THIS icon with THIS memcap and could not build it. The
      # outcome is recorded rather than inferred from the app's absence,
      # because those two states look identical from the filesystem and a
      # ~4-second osacompile/sips/codesign build retried on every 60-second
      # pass is a performance bug, not resilience. A changed NOTIFY_ICON or an
      # upgraded memcap changes the stamp; `memcap notify` ignores it entirely.
      return 1
      ;;
  esac

  mc_build_notifier || rc=$?
  if [ "$rc" = "0" ]; then outcome=ok; else outcome=failed; fi
  if mkdir -p "$(mc_state_dir)" 2>/dev/null; then
    printf '%s\n' "$want $outcome" > "$(mc_notifier_stamp)" 2>/dev/null || :
  fi
  return $rc
}

# `memcap notify` -- rebuild unconditionally and post one notification, so the
# icon can be seen without waiting for something to be killed.
mc_notify_command() {
  local icon stamped=ok
  icon="$(mc_notify_icon)"
  if [ -z "$icon" ]; then
    mc_remove_notifier
    printf '%s\n' "NOTIFY_ICON=none — memcap posts plain notifications (Script Editor's icon)."
  elif mc_build_notifier; then
    printf '%s\n' "Built $(mc_notifier_app) with the $icon icon."
    printf '%s\n' "If nothing appears, allow \"memcap\" in System Settings → Notifications."
  else
    stamped=failed
    printf '%s\n' "Could not build the notifier bundle — see $(mc_state_dir)/actions.log." >&2
    printf '%s\n' "Notifications still work; they will show Script Editor's icon." >&2
  fi
  printf '%s\n' "$MC_NOTIFIER_FORMAT ${icon:-none} $stamped" > "$(mc_notifier_stamp)" 2>/dev/null || :
  # Bypasses mc_notify's 300-second throttle deliberately: this command exists to
  # be looked at, and a user who ran it 30 seconds ago is asking to see it again.
  rm -f "$(mc_state_dir)/.notified" 2>/dev/null
  mc_notify "This is what memcap's notifications look like."
  return 0
}
